name: taxi_hamra
description: تطبيق طاكسي حمرا لمدينة فاس
version: 1.0.0+1

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  [cite_start]google_maps_flutter: ^2.5.0 # لعرض خريطة فاس [cite: 147]
  [cite_start]geolocator: ^10.1.0 # لتحديد موقع السائق لإرسال SOS [cite: 177]

flutter:
  uses-material-design: true
